### ISSUE TITLE
Wykład 1 - Zadanie 3

### ISSUE THREAD

**Issue by kigh350** [daftcode/daftacademy-python4beginners-autumn2019#1]
Czy w zadaniu 3 trzeba zrobić odwrócony słownik? 
Klucze powinny być unikalne a wartości w słowniku "names" nie są unialne.

**Comment by mateusz94** [comment]
W zadaniu 3 trzeba zrobić odrwócony słownik.

Trafne spostrzeżenie!

**Comment by kMatejak** [comment]
Właśnie. Jaki rezultat trzeba osiągnąć, żeby przejść testy? Dodaję do tego jednego powtarzającego się imienia (klucza) wartości w różnych konfiguracjach - jako tupla (2, 4), jako lista [2, 4], czy sprawdzając jedną, albo drugą opcję ('jeżeli klucz już jest - zostaw', bądź 'jeżeli klucz już jest - nadpisz'). I... nie przechodzi testów. Może nie rozumiem czegoś fundamentalnego. Już nawet nie wiem jak i czego szukać.

**Comment by kMatejak** [comment]
Wygląda na to, że musiałem mieć jakieś cashe z wcześniejszych sesji w przeglądarce - lub cokolwiek takiego. Teraz przechodzi mi testy tak z {'Marcin': 2} jak i {'Marcin': 4}.

**Comment by Pikul1994** [comment]
Ja też miałem problem z nie przechodzeniem testu (w zadaniu #4), ale po odświeżeniu sesji repl.it przeszło bez problemu :)
