### ISSUE TITLE
Wykład 3 - Zadanie 1 Klasa czy zmienna mutowalna?

### ISSUE THREAD

**Issue by Obsttube** [daftcode/daftacademy-python4beginners-autumn2019#11]
W treści zadania nr 1 (wykł. 3) jest "Ta klasa ma być mutowalna".
Na pewno chodzi o to, żeby klasa była mutowalna, czy może jednak chodzi o to, aby zmienna przechowująca w klasie wielomian miała być mutowalna?

**Comment by mateusz94** [comment]
Klasa :)
Zmienna przechowująca współczynniki wielomianu, jak uważasz.
