### ISSUE TITLE
Wykład 3 - Zadanie 8

### ISSUE THREAD

**Issue by mateusz94** [daftcode/daftacademy-python4beginners-autumn2019#13]
Wrzuciłem  jeszcze jedno zadanko!

**Comment by kigh350** [comment]
o co chodzi w tym bledzie:
mamy pomnozyc klase bez argumentu?

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 106, in test_imul
    assert mp1 == mp2, "Something went wrong with: **MyPolynomial *= MyPolynomial**"
AssertionError: Something went wrong with: MyPolynomial *= MyPolynomial

**Comment by mateusz94** [comment]
Nie, to tylko wskazówka, że jest błąd w mnożeniu `imul`
