### ISSUE TITLE
Wykład 3 - Zadanie 2

### ISSUE THREAD

**Issue by mlos3** [daftcode/daftacademy-python4beginners-autumn2019#14]
Jedna z asercji w kodzie programu jest niezgodna z asercją podczas "run testu".
Chodzi o uwzględnianie w `str(MyPolynomial())` wyrazów o współczynnikach równych zero.

Czy to pomyłka, czy dodatkowe zadanie do rozwiązania? :-)
Da się "submitować" po usunięciu z kodu asercji sprzecznej z "run testem".

**Comment by mateusz94** [comment]
@mlos3 nie widzę tam pomyłki, ale też nie do końca rozumiem co piszesz.

Trochę rozszerzę kwestię tworzenia instancji MyPolynomial.

Jak tworzymy MyPolynomial(), to domyślnie powinniśmy wiedzieć, że jest to wielomian zerowy, czyli ma jeden współniczynnik a_0 = 0 (jeśli a_0 to ten wyraz wolny)

Jak tworzymy sobie MyPolynomial(0, 0, 0, 0), to te zera, które podane są a argumentach, też nie wiele znaczą, więc nie powinniśmy tego zapisywać.

**Comment by mlos3** [comment]
Na końcu kodu programu mamy:
`assert '1 + 0x^1 + 2x^2' == str(MyPolynomial(1, 0, 2))`
Kod zwracający str(MyPolynomial()) w takiej postaci (z wyrazem 0x^1) zwraca błąd w czasie "run test"
`assert "1 + 2x^2" == str(MyPolynomial(1, 0, 2))`
`AssertionError`

Run test wymaga niewypisywania wyrazów z zerowymi współczynnikami.

**Comment by mateusz94** [comment]
tak, dlatego jest tam ten assert

**Comment by mlos3** [comment]
Chodziło mi tylko o to, że te dwa asserty są ze sobą sprzeczne. Ten, który domyślnie jest w kodzie zadania trzeba usunąć żeby przejść testy. Poza tym wszystko jasne.

**Comment by mateusz94** [comment]
jesteś pewien, że mówimy o tym: Wykład 3 - Zadanie 2?

Nigdzie nie widzę linijki: assert '1 + 0x^1 + 2x^2' == str(MyPolynomial(1, 0, 2))
