### ISSUE TITLE
wyklad 3 zad1. 

### ISSUE THREAD

**Issue by kigh350** [daftcode/daftacademy-python4beginners-autumn2019#15]
Cześć, 
trochę nie rozumiem polecenia w zadaniu pierwszym. Co dokładnie tam trzeba zrobić?
Pojawia mi się taki błąd.

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 58, in test_attr
    assert any(["_MyPolynomial__" in name for name in MyPolynomial().__dict__.keys()])
AssertionError

**Comment by mateusz94** [comment]
A masz zmienną `prywatną`?

**Comment by kigh350** [comment]
Dzięki. Przydała się podpowiedź. :)

**Comment by HasuNoHana** [comment]
Hej, mam zmienną prywatną a mimo to otrzymuję błąd:
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 44, in test_attr
    assert any(["_MyPolynomial__" in name for name in MyPolynomial().__dict__.keys()])
AssertionError

**Comment by mateusz94** [comment]
Zrob ją prywatniejszą jeszcze.

**Comment by BartoszDorobek** [comment]
Cześć, widzę, że ten assert sprawdza czy mam pole które nazywa się `MyPolynomial_`, jak dodam coś takiego `self.MyPolynomial_ =  ` to jeden z testów przechodzi, ale  domyślam się że nie o to chodziło. Co muszę zrobić aby ten assert mi przeszedł? W ogóle nie ma czegoś takiego jak `dict` sprawdzałem to na `__dict__`.

**Comment by mateusz94** [comment]
@BartoszDorobek no nie o to. repl.it źle wyświetlił ten assert. Oczywiście tam było `__dict__`. Neleżalo utworzyć w klasie zmienną prywatną i ten test to sprawdzał.
