### ISSUE TITLE
wyklad 3 zad 6

### ISSUE THREAD

**Issue by kigh350** [daftcode/daftacademy-python4beginners-autumn2019#16]
czy w zad 5 powinna byc jeszcze metoda from_iterable? 

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 33, in test_degree
    assert **MyPolynomial.from_iterable([0, 1, 0]).degree()** == 1
AttributeError: type object 'MyPolynomial' has no attribute 'from_iterable'

**Comment by having-fun** [comment]
Podbijam ;)
Jeżeli ktoś nie jest w stanie zrobić zadania nr 5, nie da rady również przejść testów do tego zadania - które miało sprawdzać inne umiejętności. Czy byłaby możliwość usunięcia z testów do tego zadania testowania metody 'from.iterable'? ;)

**Comment by mateusz94** [comment]
W zadaniu 6 zakładamy, że zadanie 5 jest już wykonane i chcielibyśmy użyć tej metody tak jak używamy metody __eq__ prawie w każdym teście.

Nie usuniemy tego testu, metoda `from_iterable` powinna być zaimplementowana.
Nie jest trudna do napisania, a ważna.
