### ISSUE TITLE
Wykład 3 - Zadanie 5

### ISSUE THREAD

**Issue by suguure** [daftcode/daftacademy-python4beginners-autumn2019#18]
Cześć, czy można liczyć na jakąś drobną podpowiedź do tego zadania? Wypróbowałam już wiele możliwości i brakuje mi pomysłów, a to zadanie jest bardzo przydatne w kolejnych.

**Comment by mateusz94** [comment]
Należy napisać metodę from_iterable, która tworzy instancję klasy MyPolynomial.
asserty są podpowiedzią o co chodzi. Marcin na wykładzie opowiadał, kiedy robimy takie rzeczy i dlaczego, polecam zajrzeć do wykladu

**Comment by suguure** [comment]
Zmyliło mnie to, że napis from_iterable doprowadził mnie do lektury na temat itertools 😆 a to było przecież takie proste.
