### ISSUE TITLE
Wykład 1 - Zadanie 1

### ISSUE THREAD

**Issue by izaszopa** [daftcode/daftacademy-python4beginners-autumn2019#2]
Mam taki dziwny problem, jak przeprowadzam testy zadania 1 to otrzymuję błąd:
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 41, in test_correctness
    assert result[0] == '🐕❤️🐍'
AssertionError

jednak w zewnętrznym programie nie mam tego błędu oraz wpisałam linijkę:
print(result[0] == '🐕🐕🐕')
i otrzymuję z tego wartość True

Co robię nie tak?

**Comment by izaszopa** [comment]
dopiero jak tutaj napisałam to kwadraciki mi się zmieniły na postaci

**Comment by mateusz94** [comment]
@izaszopa świetnie że się w końcu pokazały
