### ISSUE TITLE
Zadanie 3

### ISSUE THREAD

**Issue by badochov** [daftcode/daftacademy-python4beginners-autumn2019#21]
Info o tym że MyPolinomial jest poprawnym argumentem wejściowym jest odpiero w zadaniu 4.
Dodatkowow zzadani 4 było trochę później wstawione co sprawiało zrobienie zadania 3 niemożliwym a teraz powoduje to i tak dużo frustracji

**Comment by webster58** [comment]
Racja, błąd w testach po zmianie kolejności zadań.
Przeprasza za niedopatrzenie, zostanie poprawione jutro.

**Comment by webster58** [comment]
Poprawione. Nie ma już tego testu.
