### ISSUE TITLE
Modelowe rozwiązanie wszystkich zadań widoczne po zrobieniu pierwszego

### ISSUE THREAD

**Issue by Obsttube** [daftcode/daftacademy-python4beginners-autumn2019#24]
To normalne, że po zrobieniu pierwszego zadania z wykładu czwartego wyświetliło mi się:

> You've completed this assignment. See Model Solution

?

Po kliknięciu na "See Model Solution" przenosi mnie na stronę, gdzie jest **rozwiązanie do wszystkich zadań** (1-4). (Zrobiłem tylko pierwsze.)

**Comment by webster58** [comment]
Tak .... to właściwie nie było modelowe rozwiązanie tego zadania, ale zeszłorocznego. Błąd który wkradł się po operacjach tworzenia nowego "classroom" na repl.it na podstawie zeszłorocznego.
Rozwiązania usunięte, Jeśli podpowiedziały to super.
