### ISSUE TITLE
Brak pracy domowej na 17.12

### ISSUE THREAD

**Issue by sztach** [daftcode/daftacademy-python4beginners-autumn2019#25]
Hej,

nie było mnie ostatni tydzień w Polsce, więc w szczególności nie przyszedłem na ostatnie zajęcia. Jak rozumiem, nie ma zadanej pracy domowej na jutro? 

Dzięki za odpowiedż! :)

**Comment by Obsttube** [comment]
Nie ma, zamknij issue.
