### ISSUE TITLE
Wykład 2 - Zadanie 4

### ISSUE THREAD

**Issue by matib99** [daftcode/daftacademy-python4beginners-autumn2019#3]
W treści zadania jest mowa o ciągu 'pentagonal number series', podczas gdy testy przechodzi n pierwszych wyrazów ciągu hexagonalnego.

**Comment by mateusz94** [comment]
@matib99 racja, chodzi o hexagonal.

**Comment by OleksandrBieliakov** [comment]
W testach w jednym miejscu funkcja nazywa się pentagonal_list (), w innym hexagonal_list(), dzięki czemu nie można przejść testów. Chyba że zdefiniować obie.

**Comment by KlaudiaBrz** [comment]
Wydaje mi się, że mam dobry wynik, a nie przechodzi mi testów :(
wynik dla hexagonal_list(6) to [1, 6, 15, 28, 45, 66]
Możesz proszę podpowiedzieć co jest nie tak?

**Comment by mateusz94** [comment]
to jest problemem:
```python
return print(lista)
```
nie zwracasz listy :3
