### ISSUE TITLE
Wykład 2 - zadanie 5

### ISSUE THREAD

**Issue by HasuNoHana** [daftcode/daftacademy-python4beginners-autumn2019#6]
Czego może dotyczyć błąd:
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 29, in test_suma_dzielnikow
    assert "def suma_dzielnikow" in inspect.getsource(doskonale)
AssertionError
Program zwraca to co powinien, funkcja suma_dzielnikow zwraca sumę dzielników tak jak powinna. Wszystko wygląda jak powinno.

**Comment by mateusz94** [comment]
a gdzie jest zdefiniowana ta funkcja?

**Comment by HasuNoHana** [comment]
Nad funkcją doskonale

**Comment by mateusz94** [comment]
w poleceniu jest inaczej :dagger:

**Comment by HasuNoHana** [comment]
:o

**Comment by KlaudiaBrz** [comment]
Robię zgodnie z polecenie funkcję suma_dzielnikow(n) w funkcji doskonale(n), dla np doskonale(10000) wychodzi mi wynik [6, 28, 496, 8128], a funkcja doskonale nie przechodzi testów (za to suma_dzielnikow przechodzi). Co może być problemem?

**Comment by mateusz94** [comment]
zdaje się, że to:
```
return print(lista)
```

**Comment by KlaudiaBrz** [comment]
dzięki, działa :D
