### ISSUE TITLE
termin prac domowych

### ISSUE THREAD

**Issue by Anhithe** [daftcode/daftacademy-python4beginners-autumn2019#7]
Termin prac domowych z wykladu nr 1 byl do wtorku do 8 AM, a prac z wykladu nr 2 jest do poniedziałku do 8 PM. Dlaczego taka zmiana i pytanie czy moglby byc jednak termin taki sam jak poprzednio?

**Comment by mateusz94** [comment]
Ustawione na wtorkowy poranek.
