### ISSUE TITLE
Klikanie "help" na repl.it

### ISSUE THREAD

**Issue by mateusz94** [daftcode/daftacademy-python4beginners-autumn2019#8]
Cześć, klikanie że oczekujecie pomocy na repl.it umożliwia nam oglądanie rozwiązania jakie tam umieściliście.

**Comment by having-fun** [comment]
W którym miejscu jest możliwość kliknięcia "help"? Nie mogę jej namierzyć :P

**Comment by kMatejak** [comment]
Jak wyżej: też nie widzę "help" ;)

**Comment by mateusz94** [comment]
"submit" :D
